{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "sveda-server.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "sveda-server.labels" . | nindent 4 }}
{{- end }}
